name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  # Lint and Test
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

  # Security Scan
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"
