name: Quality Assurance & Testing

# TEMPORARILY DISABLED - Enable after fixing GitHub billing
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Kör dagligen kl 2 AM UTC
    - cron: '0 2 * * *'

env:
  NODE_VERSION: '18'
  COVERAGE_THRESHOLD: '80'

jobs:
  # Frontend Quality Checks
  frontend-quality:
    name: Frontend Quality
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Lint check
        working-directory: frontend
        run: npm run lint
        
      - name: Type check
        working-directory: frontend
        run: npm run type-check
        
      - name: Run tests
        working-directory: frontend
        run: npm run test:run
        
      - name: Test coverage
        working-directory: frontend
        run: npm run test:coverage
        
      - name: Performance tests
        working-directory: frontend
        run: npm run test:performance
        
      - name: Accessibility tests
        working-directory: frontend
        run: npm run test:accessibility
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage

  # Backend Quality Checks
  backend-quality:
    name: Backend Quality
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

  # Integration Testing
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    needs: [frontend-quality, backend-quality]
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

  # Performance Testing
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    needs: [frontend-quality]
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

  # Security Scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

  # Quality Gate
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    needs: [frontend-quality, backend-quality, security-scan]
    
    steps:
      - name: Temporarily disabled
        run: echo "Job disabled - fix GitHub billing first"

# Note: Cache configuration is handled within individual jobs using actions/setup-node@v4
